input_files:
  - path: /pscratch/sd/n/nacc/training_data/hpx64_1980-2025_dltm-v4_atmos-trainset.zarr
    channel_in:
    - NDVI_gapfill
    - swvl1
    - stl1
    - q2m
    - tcwv
    - q850
    - z1000
    - t2m
    - ttr6
    - tp6
  - path: /global/cfs/projectdirs/m4935/HPX64_dlsm/era5_hpx64_1980.zarr
    channel_in:
    - sst
    - z500
    - tau300-700
    - t850
    - z250
    - ws10m
    - ttr-3h
output_files:
  - path: /pscratch/sd/n/nacc/training_data/hpx64_1980-2025_dltm-v4_atmos-trainset.zarr
    channel_out:
    - q2m
    - tcwv
    - q850
    - z1000
    - t2m
    - ttr6
  - path: /global/cfs/projectdirs/m4935/HPX64_dlsm/era5_hpx64_1980.zarr
    channel_out:
    - sst
    - z500
    - tau300-700
    - t850
    - z250
    - ws10m
    - ttr-3h
constant_files:
  - path: /pscratch/sd/n/nacc/training_data/hpx64_1980-2025_dltm-v4_atmos-trainset.zarr
    channel_c:
    - lsm
    - z
    - NDVI_gapfill_min
    - NDVI_gapfill_max
    - NDVI_gapfill_annual_range
    - swvl1_min
    - swvl1_max
    - swvl1_annual_range
    - stl1_min
    - stl1_max
    - stl1_annual_range
time_subset_start: 1980-01-01T00:00:00
# time_subset_start: 2024-12-21T00:00:00
time_subset_end: 2024-12-31T00:00:00
time_subset_freq: 3h
output_file: /pscratch/sd/n/nacc/training_data/hpx64_1980-2025_dltm-v4_atmos-trainset_full.zarr
chunks:
  time: 1
  face: -1
  height: -1
  width: -1
overwrite: True